name: carl
channels:
  - pytorch
  - plotly
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - asttokens=2.0.5
  - backcall=0.2.0
  - blas=1.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2024.11.26
  - certifi=2024.12.14
  - charset-normalizer=2.0.4
  - cloudpickle=2.1.0
  - comm=0.2.1
  - cryptography=37.0.1
  - cudatoolkit=11.3.1
  - debugpy=1.6.7
  - decorator=5.1.1
  - exceptiongroup=1.2.0
  - executing=0.8.3
  - ffmpeg=4.3.2
  - freetype=2.10.4
  - future=0.18.2
  - giflib=5.2.1
  - gmp=6.2.1
  - gnutls=3.6.13
  - gym=0.21.0
  - gym-box2d=0.21.0
  - idna=3.3
  - importlib_metadata=8.5.0
  - intel-openmp=2022.0.1
  - ipykernel=6.29.5
  - ipython=8.15.0
  - jedi=0.19.2
  - jpeg=9e
  - jupyter_client=8.6.0
  - jupyter_core=5.7.2
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.40
  - libblas=3.9.0
  - libcblas=3.9.0
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgfortran-ng=12.1.0
  - libgfortran5=12.1.0
  - libgomp=11.2.0
  - liblapack=3.9.0
  - libopenblas=0.3.20
  - libpng=1.6.37
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libtiff=4.2.0
  - libuv=1.40.0
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - lz4-c=1.9.3
  - matplotlib-inline=0.1.6
  - mkl=2022.0.1
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - nettle=3.6
  - openh264=2.1.1
  - openssl=1.1.1w
  - parso=0.8.4
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=24.2
  - platformdirs=3.10.0
  - plotly-orca=1.3.1
  - prompt-toolkit=3.0.43
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pyopenssl=22.0.0
  - pysocks=1.7.1
  - python=3.9.18
  - python_abi=3.9
  - pytorch-mutex=1.0
  - pyzmq=26.2.0
  - readline=8.2
  - requests=2.27.1
  - setuptools=75.1.0
  - six=1.16.0
  - sqlite=3.45.3
  - stack_data=0.2.0
  - tk=8.6.14
  - torchvision=0.12.0
  - tornado=6.4.2
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - tzdata=2024b
  - urllib3=1.26.9
  - wcwidth=0.2.5
  - wheel=0.44.0
  - x264=1!161.3030
  - xz=5.4.6
  - zeromq=4.3.5
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
      - absl-py==1.1.0
      - alembic==1.8.0
      - antlr4-python3-runtime==4.9.3
      - attrs==21.4.0
      - autopage==0.5.1
      - bc==0.0.1
      - beautifulsoup4==4.11.1
      - blinker==1.9.0
      - box2d-py==2.3.5
      - brax==0.9.3
      - bs4==0.0.1
      - cachetools==5.2.0
      - cffi==1.17.1
      - chardet==4.0.0
      - chex==0.1.3
      - click==8.1.3
      - cliff==3.10.1
      - cmaes==0.8.2
      - cmd2==2.4.1
      - colorama==0.4.5
      - colorlog==6.6.0
      - commonmark==0.9.1
      - configargparse==1.5.3
      - configspace==1.2.1
      - contextlib2==21.6.0
      - cycler==0.11.0
      - dataclasses==0.6
      - dataproperty==0.55.0
      - dm-env==1.6
      - dm-tree==0.1.7
      - docker-pycreds==0.4.0
      - etils==1.5.2
      - farama-notifications==0.0.4
      - filelock==3.16.1
      - flask==3.1.0
      - flask-cors==5.0.0
      - flatbuffers==2.0
      - flax==0.5.1
      - fonttools==4.33.3
      - fsspec==2024.12.0
      - gitdb==4.0.9
      - gitpython==3.1.27
      - glfw==2.8.0
      - google-auth==2.8.0
      - google-auth-oauthlib==0.4.6
      - greenlet==1.1.2
      - grpcio==1.46.3
      - gym-notices==0.0.7
      - gymnasium==1.0.0
      - importlib-metadata==4.11.4
      - importlib-resources==6.4.5
      - itsdangerous==2.2.0
      - jax==0.4.6
      - jax-jumpy==1.0.0
      - jaxlib==0.4.6
      - jaxopt==0.8.3
      - jdk4py==21.0.2.1
      - jinja2==3.1.4
      - joblib==1.4.2
      - kaleido==0.2.1
      - kiwisolver==1.4.3
      - mako==1.2.0
      - markdown==3.3.7
      - markupsafe==2.1.1
      - matplotlib==3.5.2
      - mbstrdecoder==1.1.0
      - ml-collections==0.1.1
      - ml-dtypes==0.5.0
      - more-itertools==10.5.0
      - mpmath==1.3.0
      - msgpack==1.0.4
      - mujoco==3.0.1
      - networkx==3.2.1
      - numpy==1.22.4
      - numpyencoder==0.3.0
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - oauthlib==3.2.0
      - omegaconf==2.3.0
      - opencv-python==4.10.0.84
      - opt-einsum==3.3.0
      - optax==0.1.2
      - optuna==2.10.1
      - packaging==21.3
      - pandas==1.4.2
      - pathtools==0.1.2
      - pathvalidate==2.5.0
      - pbr==5.9.0
      - pillow==9.1.1
      - prettytable==3.3.0
      - promise==2.3
      - protobuf==3.19.4
      - psutil==5.9.1
      - py4j==0.10.9.8
      - pyasn1==0.4.8
      - pyasn1-modules==0.2.8
      - pygame==2.6.1
      - pyglet==1.5.26
      - pygments==2.12.0
      - pyopengl==3.1.7
      - pyparsing==3.0.9
      - pyperclip==1.8.2
      - pytablewriter==0.64.2
      - python-dateutil==2.8.2
      - pytinyrenderer==0.0.13
      - pytz==2022.1
      - pyvirtualdisplay==3.0
      - pyyaml==6.0
      - requests-oauthlib==1.3.1
      - rich==11.1.0
      - rsa==4.8
      - sb3-contrib==1.5.0
      - scikit-learn==1.6.0
      - scipy==1.13.1
      - sentry-sdk==1.5.12
      - setproctitle==1.2.3
      - shortuuid==1.0.9
      - sklearn==0.0
      - smmap==5.0.0
      - soupsieve==2.3.2.post1
      - sqlalchemy==1.4.37
      - stable-baselines3==2.4.0
      - stevedore==3.5.0
      - swig==4.3.0
      - sympy==1.13.1
      - tabledata==1.3.0
      - tabulate==0.8.9
      - tcolorpy==0.1.2
      - tensorboard==2.9.1
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - tensorboardx==2.5.1
      - threadpoolctl==3.5.0
      - toolz==0.11.2
      - torch==2.5.1
      - tqdm==4.64.0
      - trimesh==3.12.6
      - triton==3.1.0
      - typepy==1.3.0
      - wandb==0.12.18
      - werkzeug==3.1.3
      - xvfbwrapper==0.2.9
      - zipp==3.8.0
